# Configuration file for https://github.com/actions/labeler

"tool: cert":
  - changed-files:
    - cert/*

"tool: deliver":
  - changed-files:
    - deliver/*

"tool: fastlane_core":
  - changed-files:
    - fastlane_core/*

"tool: frameit":
  - changed-files:
    - frameit/*

"tool: gym":
  - changed-files:
    - gym/*

"tool: match":
  - changed-files:
    - match/*

"tool: pem":
  - changed-files:
    - pem/*

"tool: pilot":
  - changed-files:
    - pilot/*

"tool: precheck":
  - changed-files:
    - precheck/*

"tool: produce":
  - changed-files:
    - produce/*

"tool: scan":
  - changed-files:
    - scan/*

"tool: screengrab":
  - changed-files:
    - screengrab/*

"tool: sigh":
  - changed-files:
    - sigh/*

"tool: snapshot":
  - changed-files:
    - snapshot/*

"tool: spaceship":
  - changed-files:
    - spaceship/*

"tool: supply":
  - changed-files:
    - supply/*

"type: ci":
  - changed-files:
    - .github/*
    - .circleci/*
