# Specialized Rubocop settings for CI that place the cache directory
# in a known location that we can ask to be cached between builds
#
# We don't want to specify this for non-CI builds because the default
# behavior is better, in that it uses a system-appropriate temp dir
# location. '/tmp' is not an appropriate file root for all systems,
# but on CI we can control what kind of system we are running on.
inherit_from:
  - .rubocop.yml

AllCops:
  CacheRootDirectory: '/tmp/rubocop'
