version: 2

jobs:
  "rspec only":
    docker:
      - image: fastlanetools/fastlane:2.3.4
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle

      - run: bundle exec rspec

  "Execute tests on Ubuntu":
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      FASTLANE_ITUNES_TRANSPORTER_PATH: .bundle
    docker:
      - image: fastlanetools/fastlane:2.3.4
    steps:
      - checkout

      - restore_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
          paths:
            - .bundle

      - run:
          name: Check PR Metadata
          command: bundle exec danger || echo "danger failed"

      - restore_cache:
          key: v1-{{ arch }}-rubocop

      - run: bundle exec fastlane execute_tests

      - save_cache:
          key: v1-{{ arch }}-rubocop
          paths:
            - ~/.cache/rubocop_cache
      - store_test_results:
          path: ~/test-reports
      - store_artifacts:
          path: ~/test-reports/rspec
          destination: test-reports

      - run:
          name: Post Test Results to GitHub
          command: bundle exec danger || echo "danger failed"
          when: always # Run this even when tests fail

  "Validate Documentation":
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      
      - restore_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
      - run:
          name: Setup Build
          command: |
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
          paths:
            - .bundle

      - run: bundle exec fastlane validate_docs

  "Lint Source Code":
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout

      - restore_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
      - run:
          name: Setup Build
          command: |
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
          paths:
            - .bundle

      - run: bundle exec fastlane lint_source

workflows:
  version: 2
  build:
    jobs:
      - "Execute tests on Ubuntu"
      - "Validate Documentation"
      - "Lint Source Code"
      - "rspec only"
