name: Closing stale issues
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 7
        stale-issue-message: > 
          There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
          
          Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment :+1:
          
          Friendly reminder: contributions are always welcome! Check out [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) for more information on how to help with `fastlane` and feel free to tackle this issue yourself :muscle:
        stale-pr-message: 'There has not been any activity on this pull request recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old pull requests. Let us know if the work is still in-progress by adding a comment :+1:'
        stale-issue-label: 'status: waiting-for-reply'
        exempt-issue-label: 'status: auto-closed'
        stale-pr-label: 'status: needs-attention'
        exempt-pr-label: 'status: auto-closed'
