---
name: Version Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release_version:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install fastlane
      run: bundle install

    - name: Run fastlane
      env:
        GITHUB_API_BEARER: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER_NAME: fastlane # Todo: This is needed for docs - remove somehow
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Todo: This is needed for docs - remove somehow
        GITHUB_API_BEARER: ${{ secrets.GITHUB_TOKEN }}
        FL_GITHUB_RELEASE_API_BEARER: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec fastlane release